CREATE TABLE rooms (
   id SERIAL PRIMARY KEY,
   name VARCHAR(255),
    UNIQUE (name)
);

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    room INT,
    FOREIGN KEY (room) REFERENCES rooms(id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS messages(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    sender VARCHAR(50) NOT NULL,
    text VARCHAR(200),
    date_time TIMESTAMP,
    room INT,
    FOREIGN KEY (sender) REFERENCES users(name),
    FOREIGN KEY (room) REFERENCES rooms(id)
);

